apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wta
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/natalicot/WTA_K8s.git
    targetRevision: master
    path: wta/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true # if resource deleted - delete it
      selfHeal: false # changes that are made to the live cluster will not trigger automated sync